Desktop-version
BonkeGcobo/Portfolio pull request #7
Opened 2021-08-27 17:50 UTC by BonkeGcobo

We created the mobile version of the project

2021-08-27 19:03 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Bonke Gcobo, 
 ### You have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [x] GitHub flow is used properly.
- [ ] Linter checks are passing.
## To Improve 🙏
- [ ] Please check inline comments under the review
## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-08-27 19:03 UTC, SajjadAhmad14 commented on css/myStyle.css
> +@media only screen and (min-width: 915px) {
Please make sure the value for min-width property should be in range of 992px - 1100px.

2021-08-27 19:03 UTC, SajjadAhmad14 commented on css/myStyle.css
>  .headline {
Please use the same font color for headline text and `let's connect` text. Moreover, there is a round border on the bottom left of the section in the original design. Kindly see the below screenshot and fix issues accordingly.
![intro](https://user-images.githubusercontent.com/35504149/131176057-a0fe0a87-cac4-44af-94fa-70164e4c376e.png)

2021-08-27 19:03 UTC, SajjadAhmad14 commented on Portfolio.html
>    <section class="Works">
Please add a border to project cards as it's in the design. Moreover please use `Poppins font for all the whole content and use the same color from the design.

2021-08-27 19:03 UTC, SajjadAhmad14 commented on Portfolio.html
> +      </div>
The `About me` section should have a button to get the resume. Moreover, please use the same font color from the design.

2021-08-27 19:03 UTC, SajjadAhmad14 commented on Portfolio.html
Contact form heading should be in the center of the form. Please see the below screenshot for reference.
![contact](https://user-images.githubusercontent.com/35504149/131175901-de76c581-47bb-48a3-95e9-17347ae06040.png)

2021-08-27 19:03 UTC, SajjadAhmad14 commented on Portfolio.html
>        </div>
Please add a project description of the features and add instructions to set the project up locally in README. Moreover, PR should have a descriptive summary of project features.

2021-08-27 19:03 UTC, SajjadAhmad14 commented on css/myStyle.css
>  }
[ OPTIONAL ] Please make an assets folder and put all of your images and other assets in it. The project directory will look nice and managed.

2021-08-28 11:13 UTC, BonkeGcobo commented on css/myStyle.css
>  .headline {
Okay thank you, Sajjad however in the figma design the let's connect and the headline text have different colors

2021-08-28 12:54 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Bonke Gcobo, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-08-28 14:23 UTC, merged